# Generated by Django 5.2.6 on 2025-09-28 13:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="category",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="level",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="tag",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent tag (None for top-level categories)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="news.tag",
            ),
        ),
    ]
