# Generated by Django 5.2.6 on 2025-09-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_simplify_tag_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="parent",
        ),
    ]
