# Generated by Django 5.2.6 on 2025-09-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_remove_tag_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent tag for hierarchical relationships",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="news.tag",
            ),
        ),
    ]
